import torch
import torch.nn as nn
import torch.nn.functional as F

class resnet50_v1d_11(nn.Module):
    def __init__(self):
        super(resnet50_v1d_11, self).__init__()
        self.resnetv1d_conv0_fwd = nn.Conv2d(3, 8, kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_batchnorm0_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_relu0_fwd = nn.ReLU()
        self.resnetv1d_conv1_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_batchnorm1_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_relu1_fwd = nn.ReLU()
        self.resnetv1d_conv2_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_batchnorm2_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_relu2_fwd = nn.ReLU()
        self.resnetv1d_pool0_fwd = nn.MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), ceil_mode=False)
        self.resnetv1d_layers1_conv0_fwd = nn.Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers1_batchnorm0_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers1_relu0_fwd = nn.ReLU()
        self.resnetv1d_layers1_conv1_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers1_batchnorm1_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers1_relu1_fwd = nn.ReLU()
        self.resnetv1d_layers1_conv2_fwd = nn.Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers1_batchnorm2_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_down1_pool0_fwd = nn.AvgPool2d(kernel_size=(1, 1), stride=(1, 1), padding=(0, 0), count_include_pad=False, ceil_mode=True)
        self.resnetv1d_down1_conv0_fwd = nn.Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_down1_batchnorm0_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers1_relu2_fwd = nn.ReLU()
        self.resnetv1d_layers1_conv3_fwd = nn.Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers1_batchnorm3_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers1_relu3_fwd = nn.ReLU()
        self.resnetv1d_layers1_conv4_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers1_batchnorm4_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers1_relu4_fwd = nn.ReLU()
        self.resnetv1d_layers1_conv5_fwd = nn.Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers1_batchnorm5_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers1_relu5_fwd = nn.ReLU()
        self.resnetv1d_layers1_conv6_fwd = nn.Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers1_batchnorm6_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers1_relu6_fwd = nn.ReLU()
        self.resnetv1d_layers1_conv7_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers1_batchnorm7_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers1_relu7_fwd = nn.ReLU()
        self.resnetv1d_layers1_conv8_fwd = nn.Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers1_batchnorm8_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers1_relu8_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv0_fwd = nn.Conv2d(8, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers2_batchnorm0_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu0_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv1_fwd = nn.Conv2d(8, 24, kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers2_batchnorm1_fwd = nn.BatchNorm2d(24, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu1_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv2_fwd = nn.Conv2d(24, 16, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers2_batchnorm2_fwd = nn.BatchNorm2d(16, momentum=0.9, eps=1e-05)
        self.resnetv1d_down2_pool0_fwd = nn.AvgPool2d(kernel_size=(2, 2), stride=(2, 2), padding=(0, 0), count_include_pad=False, ceil_mode=True)
        self.resnetv1d_down2_conv0_fwd = nn.Conv2d(8, 16, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_down2_batchnorm0_fwd = nn.BatchNorm2d(16, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu2_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv3_fwd = nn.Conv2d(16, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers2_batchnorm3_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu3_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv4_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers2_batchnorm4_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu4_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv5_fwd = nn.Conv2d(8, 16, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers2_batchnorm5_fwd = nn.BatchNorm2d(16, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu5_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv6_fwd = nn.Conv2d(16, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers2_batchnorm6_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu6_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv7_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers2_batchnorm7_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu7_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv8_fwd = nn.Conv2d(8, 16, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers2_batchnorm8_fwd = nn.BatchNorm2d(16, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu8_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv9_fwd = nn.Conv2d(16, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers2_batchnorm9_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu9_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv10_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers2_batchnorm10_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu10_fwd = nn.ReLU()
        self.resnetv1d_layers2_conv11_fwd = nn.Conv2d(8, 16, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers2_batchnorm11_fwd = nn.BatchNorm2d(16, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers2_relu11_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv0_fwd = nn.Conv2d(16, 8, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm0_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu0_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv1_fwd = nn.Conv2d(8, 16, kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers3_batchnorm1_fwd = nn.BatchNorm2d(16, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu1_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv2_fwd = nn.Conv2d(16, 80, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm2_fwd = nn.BatchNorm2d(80, momentum=0.9, eps=1e-05)
        self.resnetv1d_down3_pool0_fwd = nn.AvgPool2d(kernel_size=(2, 2), stride=(2, 2), padding=(0, 0), count_include_pad=False, ceil_mode=True)
        self.resnetv1d_down3_conv0_fwd = nn.Conv2d(16, 80, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_down3_batchnorm0_fwd = nn.BatchNorm2d(80, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu2_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv3_fwd = nn.Conv2d(80, 24, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm3_fwd = nn.BatchNorm2d(24, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu3_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv4_fwd = nn.Conv2d(24, 48, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers3_batchnorm4_fwd = nn.BatchNorm2d(48, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu4_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv5_fwd = nn.Conv2d(48, 80, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm5_fwd = nn.BatchNorm2d(80, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu5_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv6_fwd = nn.Conv2d(80, 56, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm6_fwd = nn.BatchNorm2d(56, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu6_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv7_fwd = nn.Conv2d(56, 208, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers3_batchnorm7_fwd = nn.BatchNorm2d(208, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu7_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv8_fwd = nn.Conv2d(208, 80, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm8_fwd = nn.BatchNorm2d(80, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu8_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv9_fwd = nn.Conv2d(80, 120, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm9_fwd = nn.BatchNorm2d(120, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu9_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv10_fwd = nn.Conv2d(120, 88, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers3_batchnorm10_fwd = nn.BatchNorm2d(88, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu10_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv11_fwd = nn.Conv2d(88, 80, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm11_fwd = nn.BatchNorm2d(80, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu11_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv12_fwd = nn.Conv2d(80, 88, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm12_fwd = nn.BatchNorm2d(88, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu12_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv13_fwd = nn.Conv2d(88, 64, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers3_batchnorm13_fwd = nn.BatchNorm2d(64, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu13_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv14_fwd = nn.Conv2d(64, 80, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm14_fwd = nn.BatchNorm2d(80, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu14_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv15_fwd = nn.Conv2d(80, 40, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm15_fwd = nn.BatchNorm2d(40, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu15_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv16_fwd = nn.Conv2d(40, 200, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers3_batchnorm16_fwd = nn.BatchNorm2d(200, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu16_fwd = nn.ReLU()
        self.resnetv1d_layers3_conv17_fwd = nn.Conv2d(200, 80, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers3_batchnorm17_fwd = nn.BatchNorm2d(80, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers3_relu17_fwd = nn.ReLU()
        self.resnetv1d_layers4_conv0_fwd = nn.Conv2d(80, 80, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers4_batchnorm0_fwd = nn.BatchNorm2d(80, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers4_relu0_fwd = nn.ReLU()
        self.resnetv1d_layers4_conv1_fwd = nn.Conv2d(80, 192, kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers4_batchnorm1_fwd = nn.BatchNorm2d(192, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers4_relu1_fwd = nn.ReLU()
        self.resnetv1d_layers4_conv2_fwd = nn.Conv2d(192, 784, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers4_batchnorm2_fwd = nn.BatchNorm2d(784, momentum=0.9, eps=1e-05)
        self.resnetv1d_down4_pool0_fwd = nn.AvgPool2d(kernel_size=(2, 2), stride=(2, 2), padding=(0, 0), count_include_pad=False, ceil_mode=True)
        self.resnetv1d_down4_conv0_fwd = nn.Conv2d(80, 784, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_down4_batchnorm0_fwd = nn.BatchNorm2d(784, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers4_relu2_fwd = nn.ReLU()
        self.resnetv1d_layers4_conv3_fwd = nn.Conv2d(784, 264, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers4_batchnorm3_fwd = nn.BatchNorm2d(264, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers4_relu3_fwd = nn.ReLU()
        self.resnetv1d_layers4_conv4_fwd = nn.Conv2d(264, 48, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers4_batchnorm4_fwd = nn.BatchNorm2d(48, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers4_relu4_fwd = nn.ReLU()
        self.resnetv1d_layers4_conv5_fwd = nn.Conv2d(48, 784, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers4_batchnorm5_fwd = nn.BatchNorm2d(784, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers4_relu5_fwd = nn.ReLU()
        self.resnetv1d_layers4_conv6_fwd = nn.Conv2d(784, 152, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers4_batchnorm6_fwd = nn.BatchNorm2d(152, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers4_relu6_fwd = nn.ReLU()
        self.resnetv1d_layers4_conv7_fwd = nn.Conv2d(152, 400, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1d_layers4_batchnorm7_fwd = nn.BatchNorm2d(400, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers4_relu7_fwd = nn.ReLU()
        self.resnetv1d_layers4_conv8_fwd = nn.Conv2d(400, 784, kernel_size=(1, 1), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1d_layers4_batchnorm8_fwd = nn.BatchNorm2d(784, momentum=0.9, eps=1e-05)
        self.resnetv1d_layers4_relu8_fwd = nn.ReLU()
        self.resnetv1d_dense0_fwd = nn.Linear(784, 1000, bias=True)

    def forward(self, __input__0):
        resnetv1d_conv0_fwd = self.resnetv1d_conv0_fwd(__input__0)
        resnetv1d_batchnorm0_fwd = self.resnetv1d_batchnorm0_fwd(resnetv1d_conv0_fwd)
        resnetv1d_relu0_fwd = self.resnetv1d_relu0_fwd(resnetv1d_batchnorm0_fwd)
        resnetv1d_conv1_fwd = self.resnetv1d_conv1_fwd(resnetv1d_relu0_fwd)
        resnetv1d_batchnorm1_fwd = self.resnetv1d_batchnorm1_fwd(resnetv1d_conv1_fwd)
        resnetv1d_relu1_fwd = self.resnetv1d_relu1_fwd(resnetv1d_batchnorm1_fwd)
        resnetv1d_conv2_fwd = self.resnetv1d_conv2_fwd(resnetv1d_relu1_fwd)
        resnetv1d_batchnorm2_fwd = self.resnetv1d_batchnorm2_fwd(resnetv1d_conv2_fwd)
        resnetv1d_relu2_fwd = self.resnetv1d_relu2_fwd(resnetv1d_batchnorm2_fwd)
        resnetv1d_pool0_fwd = self.resnetv1d_pool0_fwd(resnetv1d_relu2_fwd)
        resnetv1d_layers1_conv0_fwd = self.resnetv1d_layers1_conv0_fwd(resnetv1d_pool0_fwd)
        resnetv1d_layers1_batchnorm0_fwd = self.resnetv1d_layers1_batchnorm0_fwd(resnetv1d_layers1_conv0_fwd)
        resnetv1d_layers1_relu0_fwd = self.resnetv1d_layers1_relu0_fwd(resnetv1d_layers1_batchnorm0_fwd)
        resnetv1d_layers1_conv1_fwd = self.resnetv1d_layers1_conv1_fwd(resnetv1d_layers1_relu0_fwd)
        resnetv1d_layers1_batchnorm1_fwd = self.resnetv1d_layers1_batchnorm1_fwd(resnetv1d_layers1_conv1_fwd)
        resnetv1d_layers1_relu1_fwd = self.resnetv1d_layers1_relu1_fwd(resnetv1d_layers1_batchnorm1_fwd)
        resnetv1d_layers1_conv2_fwd = self.resnetv1d_layers1_conv2_fwd(resnetv1d_layers1_relu1_fwd)
        resnetv1d_layers1_batchnorm2_fwd = self.resnetv1d_layers1_batchnorm2_fwd(resnetv1d_layers1_conv2_fwd)
        resnetv1d_down1_pool0_fwd = self.resnetv1d_down1_pool0_fwd(resnetv1d_pool0_fwd)
        resnetv1d_down1_conv0_fwd = self.resnetv1d_down1_conv0_fwd(resnetv1d_down1_pool0_fwd)
        resnetv1d_down1_batchnorm0_fwd = self.resnetv1d_down1_batchnorm0_fwd(resnetv1d_down1_conv0_fwd)
        resnetv1d_layers1_bottleneckv1b0__plus0 = resnetv1d_layers1_batchnorm2_fwd + resnetv1d_down1_batchnorm0_fwd
        resnetv1d_layers1_relu2_fwd = self.resnetv1d_layers1_relu2_fwd(resnetv1d_layers1_bottleneckv1b0__plus0)
        resnetv1d_layers1_conv3_fwd = self.resnetv1d_layers1_conv3_fwd(resnetv1d_layers1_relu2_fwd)
        resnetv1d_layers1_batchnorm3_fwd = self.resnetv1d_layers1_batchnorm3_fwd(resnetv1d_layers1_conv3_fwd)
        resnetv1d_layers1_relu3_fwd = self.resnetv1d_layers1_relu3_fwd(resnetv1d_layers1_batchnorm3_fwd)
        resnetv1d_layers1_conv4_fwd = self.resnetv1d_layers1_conv4_fwd(resnetv1d_layers1_relu3_fwd)
        resnetv1d_layers1_batchnorm4_fwd = self.resnetv1d_layers1_batchnorm4_fwd(resnetv1d_layers1_conv4_fwd)
        resnetv1d_layers1_relu4_fwd = self.resnetv1d_layers1_relu4_fwd(resnetv1d_layers1_batchnorm4_fwd)
        resnetv1d_layers1_conv5_fwd = self.resnetv1d_layers1_conv5_fwd(resnetv1d_layers1_relu4_fwd)
        resnetv1d_layers1_batchnorm5_fwd = self.resnetv1d_layers1_batchnorm5_fwd(resnetv1d_layers1_conv5_fwd)
        resnetv1d_layers1_bottleneckv1b1__plus0 = resnetv1d_layers1_batchnorm5_fwd + resnetv1d_layers1_relu2_fwd
        resnetv1d_layers1_relu5_fwd = self.resnetv1d_layers1_relu5_fwd(resnetv1d_layers1_bottleneckv1b1__plus0)
        resnetv1d_layers1_conv6_fwd = self.resnetv1d_layers1_conv6_fwd(resnetv1d_layers1_relu5_fwd)
        resnetv1d_layers1_batchnorm6_fwd = self.resnetv1d_layers1_batchnorm6_fwd(resnetv1d_layers1_conv6_fwd)
        resnetv1d_layers1_relu6_fwd = self.resnetv1d_layers1_relu6_fwd(resnetv1d_layers1_batchnorm6_fwd)
        resnetv1d_layers1_conv7_fwd = self.resnetv1d_layers1_conv7_fwd(resnetv1d_layers1_relu6_fwd)
        resnetv1d_layers1_batchnorm7_fwd = self.resnetv1d_layers1_batchnorm7_fwd(resnetv1d_layers1_conv7_fwd)
        resnetv1d_layers1_relu7_fwd = self.resnetv1d_layers1_relu7_fwd(resnetv1d_layers1_batchnorm7_fwd)
        resnetv1d_layers1_conv8_fwd = self.resnetv1d_layers1_conv8_fwd(resnetv1d_layers1_relu7_fwd)
        resnetv1d_layers1_batchnorm8_fwd = self.resnetv1d_layers1_batchnorm8_fwd(resnetv1d_layers1_conv8_fwd)
        resnetv1d_layers1_bottleneckv1b2__plus0 = resnetv1d_layers1_batchnorm8_fwd + resnetv1d_layers1_relu5_fwd
        resnetv1d_layers1_relu8_fwd = self.resnetv1d_layers1_relu8_fwd(resnetv1d_layers1_bottleneckv1b2__plus0)
        resnetv1d_layers2_conv0_fwd = self.resnetv1d_layers2_conv0_fwd(resnetv1d_layers1_relu8_fwd)
        resnetv1d_layers2_batchnorm0_fwd = self.resnetv1d_layers2_batchnorm0_fwd(resnetv1d_layers2_conv0_fwd)
        resnetv1d_layers2_relu0_fwd = self.resnetv1d_layers2_relu0_fwd(resnetv1d_layers2_batchnorm0_fwd)
        resnetv1d_layers2_conv1_fwd = self.resnetv1d_layers2_conv1_fwd(resnetv1d_layers2_relu0_fwd)
        resnetv1d_layers2_batchnorm1_fwd = self.resnetv1d_layers2_batchnorm1_fwd(resnetv1d_layers2_conv1_fwd)
        resnetv1d_layers2_relu1_fwd = self.resnetv1d_layers2_relu1_fwd(resnetv1d_layers2_batchnorm1_fwd)
        resnetv1d_layers2_conv2_fwd = self.resnetv1d_layers2_conv2_fwd(resnetv1d_layers2_relu1_fwd)
        resnetv1d_layers2_batchnorm2_fwd = self.resnetv1d_layers2_batchnorm2_fwd(resnetv1d_layers2_conv2_fwd)
        resnetv1d_down2_pool0_fwd = self.resnetv1d_down2_pool0_fwd(resnetv1d_layers1_relu8_fwd)
        resnetv1d_down2_conv0_fwd = self.resnetv1d_down2_conv0_fwd(resnetv1d_down2_pool0_fwd)
        resnetv1d_down2_batchnorm0_fwd = self.resnetv1d_down2_batchnorm0_fwd(resnetv1d_down2_conv0_fwd)
        resnetv1d_layers2_bottleneckv1b0__plus0 = resnetv1d_layers2_batchnorm2_fwd + resnetv1d_down2_batchnorm0_fwd
        resnetv1d_layers2_relu2_fwd = self.resnetv1d_layers2_relu2_fwd(resnetv1d_layers2_bottleneckv1b0__plus0)
        resnetv1d_layers2_conv3_fwd = self.resnetv1d_layers2_conv3_fwd(resnetv1d_layers2_relu2_fwd)
        resnetv1d_layers2_batchnorm3_fwd = self.resnetv1d_layers2_batchnorm3_fwd(resnetv1d_layers2_conv3_fwd)
        resnetv1d_layers2_relu3_fwd = self.resnetv1d_layers2_relu3_fwd(resnetv1d_layers2_batchnorm3_fwd)
        resnetv1d_layers2_conv4_fwd = self.resnetv1d_layers2_conv4_fwd(resnetv1d_layers2_relu3_fwd)
        resnetv1d_layers2_batchnorm4_fwd = self.resnetv1d_layers2_batchnorm4_fwd(resnetv1d_layers2_conv4_fwd)
        resnetv1d_layers2_relu4_fwd = self.resnetv1d_layers2_relu4_fwd(resnetv1d_layers2_batchnorm4_fwd)
        resnetv1d_layers2_conv5_fwd = self.resnetv1d_layers2_conv5_fwd(resnetv1d_layers2_relu4_fwd)
        resnetv1d_layers2_batchnorm5_fwd = self.resnetv1d_layers2_batchnorm5_fwd(resnetv1d_layers2_conv5_fwd)
        resnetv1d_layers2_bottleneckv1b1__plus0 = resnetv1d_layers2_batchnorm5_fwd + resnetv1d_layers2_relu2_fwd
        resnetv1d_layers2_relu5_fwd = self.resnetv1d_layers2_relu5_fwd(resnetv1d_layers2_bottleneckv1b1__plus0)
        resnetv1d_layers2_conv6_fwd = self.resnetv1d_layers2_conv6_fwd(resnetv1d_layers2_relu5_fwd)
        resnetv1d_layers2_batchnorm6_fwd = self.resnetv1d_layers2_batchnorm6_fwd(resnetv1d_layers2_conv6_fwd)
        resnetv1d_layers2_relu6_fwd = self.resnetv1d_layers2_relu6_fwd(resnetv1d_layers2_batchnorm6_fwd)
        resnetv1d_layers2_conv7_fwd = self.resnetv1d_layers2_conv7_fwd(resnetv1d_layers2_relu6_fwd)
        resnetv1d_layers2_batchnorm7_fwd = self.resnetv1d_layers2_batchnorm7_fwd(resnetv1d_layers2_conv7_fwd)
        resnetv1d_layers2_relu7_fwd = self.resnetv1d_layers2_relu7_fwd(resnetv1d_layers2_batchnorm7_fwd)
        resnetv1d_layers2_conv8_fwd = self.resnetv1d_layers2_conv8_fwd(resnetv1d_layers2_relu7_fwd)
        resnetv1d_layers2_batchnorm8_fwd = self.resnetv1d_layers2_batchnorm8_fwd(resnetv1d_layers2_conv8_fwd)
        resnetv1d_layers2_bottleneckv1b2__plus0 = resnetv1d_layers2_batchnorm8_fwd + resnetv1d_layers2_relu5_fwd
        resnetv1d_layers2_relu8_fwd = self.resnetv1d_layers2_relu8_fwd(resnetv1d_layers2_bottleneckv1b2__plus0)
        resnetv1d_layers2_conv9_fwd = self.resnetv1d_layers2_conv9_fwd(resnetv1d_layers2_relu8_fwd)
        resnetv1d_layers2_batchnorm9_fwd = self.resnetv1d_layers2_batchnorm9_fwd(resnetv1d_layers2_conv9_fwd)
        resnetv1d_layers2_relu9_fwd = self.resnetv1d_layers2_relu9_fwd(resnetv1d_layers2_batchnorm9_fwd)
        resnetv1d_layers2_conv10_fwd = self.resnetv1d_layers2_conv10_fwd(resnetv1d_layers2_relu9_fwd)
        resnetv1d_layers2_batchnorm10_fwd = self.resnetv1d_layers2_batchnorm10_fwd(resnetv1d_layers2_conv10_fwd)
        resnetv1d_layers2_relu10_fwd = self.resnetv1d_layers2_relu10_fwd(resnetv1d_layers2_batchnorm10_fwd)
        resnetv1d_layers2_conv11_fwd = self.resnetv1d_layers2_conv11_fwd(resnetv1d_layers2_relu10_fwd)
        resnetv1d_layers2_batchnorm11_fwd = self.resnetv1d_layers2_batchnorm11_fwd(resnetv1d_layers2_conv11_fwd)
        resnetv1d_layers2_bottleneckv1b3__plus0 = resnetv1d_layers2_batchnorm11_fwd + resnetv1d_layers2_relu8_fwd
        resnetv1d_layers2_relu11_fwd = self.resnetv1d_layers2_relu11_fwd(resnetv1d_layers2_bottleneckv1b3__plus0)
        resnetv1d_layers3_conv0_fwd = self.resnetv1d_layers3_conv0_fwd(resnetv1d_layers2_relu11_fwd)
        resnetv1d_layers3_batchnorm0_fwd = self.resnetv1d_layers3_batchnorm0_fwd(resnetv1d_layers3_conv0_fwd)
        resnetv1d_layers3_relu0_fwd = self.resnetv1d_layers3_relu0_fwd(resnetv1d_layers3_batchnorm0_fwd)
        resnetv1d_layers3_conv1_fwd = self.resnetv1d_layers3_conv1_fwd(resnetv1d_layers3_relu0_fwd)
        resnetv1d_layers3_batchnorm1_fwd = self.resnetv1d_layers3_batchnorm1_fwd(resnetv1d_layers3_conv1_fwd)
        resnetv1d_layers3_relu1_fwd = self.resnetv1d_layers3_relu1_fwd(resnetv1d_layers3_batchnorm1_fwd)
        resnetv1d_layers3_conv2_fwd = self.resnetv1d_layers3_conv2_fwd(resnetv1d_layers3_relu1_fwd)
        resnetv1d_layers3_batchnorm2_fwd = self.resnetv1d_layers3_batchnorm2_fwd(resnetv1d_layers3_conv2_fwd)
        resnetv1d_down3_pool0_fwd = self.resnetv1d_down3_pool0_fwd(resnetv1d_layers2_relu11_fwd)
        resnetv1d_down3_conv0_fwd = self.resnetv1d_down3_conv0_fwd(resnetv1d_down3_pool0_fwd)
        resnetv1d_down3_batchnorm0_fwd = self.resnetv1d_down3_batchnorm0_fwd(resnetv1d_down3_conv0_fwd)
        resnetv1d_layers3_bottleneckv1b0__plus0 = resnetv1d_layers3_batchnorm2_fwd + resnetv1d_down3_batchnorm0_fwd
        resnetv1d_layers3_relu2_fwd = self.resnetv1d_layers3_relu2_fwd(resnetv1d_layers3_bottleneckv1b0__plus0)
        resnetv1d_layers3_conv3_fwd = self.resnetv1d_layers3_conv3_fwd(resnetv1d_layers3_relu2_fwd)
        resnetv1d_layers3_batchnorm3_fwd = self.resnetv1d_layers3_batchnorm3_fwd(resnetv1d_layers3_conv3_fwd)
        resnetv1d_layers3_relu3_fwd = self.resnetv1d_layers3_relu3_fwd(resnetv1d_layers3_batchnorm3_fwd)
        resnetv1d_layers3_conv4_fwd = self.resnetv1d_layers3_conv4_fwd(resnetv1d_layers3_relu3_fwd)
        resnetv1d_layers3_batchnorm4_fwd = self.resnetv1d_layers3_batchnorm4_fwd(resnetv1d_layers3_conv4_fwd)
        resnetv1d_layers3_relu4_fwd = self.resnetv1d_layers3_relu4_fwd(resnetv1d_layers3_batchnorm4_fwd)
        resnetv1d_layers3_conv5_fwd = self.resnetv1d_layers3_conv5_fwd(resnetv1d_layers3_relu4_fwd)
        resnetv1d_layers3_batchnorm5_fwd = self.resnetv1d_layers3_batchnorm5_fwd(resnetv1d_layers3_conv5_fwd)
        resnetv1d_layers3_bottleneckv1b1__plus0 = resnetv1d_layers3_batchnorm5_fwd + resnetv1d_layers3_relu2_fwd
        resnetv1d_layers3_relu5_fwd = self.resnetv1d_layers3_relu5_fwd(resnetv1d_layers3_bottleneckv1b1__plus0)
        resnetv1d_layers3_conv6_fwd = self.resnetv1d_layers3_conv6_fwd(resnetv1d_layers3_relu5_fwd)
        resnetv1d_layers3_batchnorm6_fwd = self.resnetv1d_layers3_batchnorm6_fwd(resnetv1d_layers3_conv6_fwd)
        resnetv1d_layers3_relu6_fwd = self.resnetv1d_layers3_relu6_fwd(resnetv1d_layers3_batchnorm6_fwd)
        resnetv1d_layers3_conv7_fwd = self.resnetv1d_layers3_conv7_fwd(resnetv1d_layers3_relu6_fwd)
        resnetv1d_layers3_batchnorm7_fwd = self.resnetv1d_layers3_batchnorm7_fwd(resnetv1d_layers3_conv7_fwd)
        resnetv1d_layers3_relu7_fwd = self.resnetv1d_layers3_relu7_fwd(resnetv1d_layers3_batchnorm7_fwd)
        resnetv1d_layers3_conv8_fwd = self.resnetv1d_layers3_conv8_fwd(resnetv1d_layers3_relu7_fwd)
        resnetv1d_layers3_batchnorm8_fwd = self.resnetv1d_layers3_batchnorm8_fwd(resnetv1d_layers3_conv8_fwd)
        resnetv1d_layers3_bottleneckv1b2__plus0 = resnetv1d_layers3_batchnorm8_fwd + resnetv1d_layers3_relu5_fwd
        resnetv1d_layers3_relu8_fwd = self.resnetv1d_layers3_relu8_fwd(resnetv1d_layers3_bottleneckv1b2__plus0)
        resnetv1d_layers3_conv9_fwd = self.resnetv1d_layers3_conv9_fwd(resnetv1d_layers3_relu8_fwd)
        resnetv1d_layers3_batchnorm9_fwd = self.resnetv1d_layers3_batchnorm9_fwd(resnetv1d_layers3_conv9_fwd)
        resnetv1d_layers3_relu9_fwd = self.resnetv1d_layers3_relu9_fwd(resnetv1d_layers3_batchnorm9_fwd)
        resnetv1d_layers3_conv10_fwd = self.resnetv1d_layers3_conv10_fwd(resnetv1d_layers3_relu9_fwd)
        resnetv1d_layers3_batchnorm10_fwd = self.resnetv1d_layers3_batchnorm10_fwd(resnetv1d_layers3_conv10_fwd)
        resnetv1d_layers3_relu10_fwd = self.resnetv1d_layers3_relu10_fwd(resnetv1d_layers3_batchnorm10_fwd)
        resnetv1d_layers3_conv11_fwd = self.resnetv1d_layers3_conv11_fwd(resnetv1d_layers3_relu10_fwd)
        resnetv1d_layers3_batchnorm11_fwd = self.resnetv1d_layers3_batchnorm11_fwd(resnetv1d_layers3_conv11_fwd)
        resnetv1d_layers3_bottleneckv1b3__plus0 = resnetv1d_layers3_batchnorm11_fwd + resnetv1d_layers3_relu8_fwd
        resnetv1d_layers3_relu11_fwd = self.resnetv1d_layers3_relu11_fwd(resnetv1d_layers3_bottleneckv1b3__plus0)
        resnetv1d_layers3_conv12_fwd = self.resnetv1d_layers3_conv12_fwd(resnetv1d_layers3_relu11_fwd)
        resnetv1d_layers3_batchnorm12_fwd = self.resnetv1d_layers3_batchnorm12_fwd(resnetv1d_layers3_conv12_fwd)
        resnetv1d_layers3_relu12_fwd = self.resnetv1d_layers3_relu12_fwd(resnetv1d_layers3_batchnorm12_fwd)
        resnetv1d_layers3_conv13_fwd = self.resnetv1d_layers3_conv13_fwd(resnetv1d_layers3_relu12_fwd)
        resnetv1d_layers3_batchnorm13_fwd = self.resnetv1d_layers3_batchnorm13_fwd(resnetv1d_layers3_conv13_fwd)
        resnetv1d_layers3_relu13_fwd = self.resnetv1d_layers3_relu13_fwd(resnetv1d_layers3_batchnorm13_fwd)
        resnetv1d_layers3_conv14_fwd = self.resnetv1d_layers3_conv14_fwd(resnetv1d_layers3_relu13_fwd)
        resnetv1d_layers3_batchnorm14_fwd = self.resnetv1d_layers3_batchnorm14_fwd(resnetv1d_layers3_conv14_fwd)
        resnetv1d_layers3_bottleneckv1b4__plus0 = resnetv1d_layers3_batchnorm14_fwd + resnetv1d_layers3_relu11_fwd
        resnetv1d_layers3_relu14_fwd = self.resnetv1d_layers3_relu14_fwd(resnetv1d_layers3_bottleneckv1b4__plus0)
        resnetv1d_layers3_conv15_fwd = self.resnetv1d_layers3_conv15_fwd(resnetv1d_layers3_relu14_fwd)
        resnetv1d_layers3_batchnorm15_fwd = self.resnetv1d_layers3_batchnorm15_fwd(resnetv1d_layers3_conv15_fwd)
        resnetv1d_layers3_relu15_fwd = self.resnetv1d_layers3_relu15_fwd(resnetv1d_layers3_batchnorm15_fwd)
        resnetv1d_layers3_conv16_fwd = self.resnetv1d_layers3_conv16_fwd(resnetv1d_layers3_relu15_fwd)
        resnetv1d_layers3_batchnorm16_fwd = self.resnetv1d_layers3_batchnorm16_fwd(resnetv1d_layers3_conv16_fwd)
        resnetv1d_layers3_relu16_fwd = self.resnetv1d_layers3_relu16_fwd(resnetv1d_layers3_batchnorm16_fwd)
        resnetv1d_layers3_conv17_fwd = self.resnetv1d_layers3_conv17_fwd(resnetv1d_layers3_relu16_fwd)
        resnetv1d_layers3_batchnorm17_fwd = self.resnetv1d_layers3_batchnorm17_fwd(resnetv1d_layers3_conv17_fwd)
        resnetv1d_layers3_bottleneckv1b5__plus0 = resnetv1d_layers3_batchnorm17_fwd + resnetv1d_layers3_relu14_fwd
        resnetv1d_layers3_relu17_fwd = self.resnetv1d_layers3_relu17_fwd(resnetv1d_layers3_bottleneckv1b5__plus0)
        resnetv1d_layers4_conv0_fwd = self.resnetv1d_layers4_conv0_fwd(resnetv1d_layers3_relu17_fwd)
        resnetv1d_layers4_batchnorm0_fwd = self.resnetv1d_layers4_batchnorm0_fwd(resnetv1d_layers4_conv0_fwd)
        resnetv1d_layers4_relu0_fwd = self.resnetv1d_layers4_relu0_fwd(resnetv1d_layers4_batchnorm0_fwd)
        resnetv1d_layers4_conv1_fwd = self.resnetv1d_layers4_conv1_fwd(resnetv1d_layers4_relu0_fwd)
        resnetv1d_layers4_batchnorm1_fwd = self.resnetv1d_layers4_batchnorm1_fwd(resnetv1d_layers4_conv1_fwd)
        resnetv1d_layers4_relu1_fwd = self.resnetv1d_layers4_relu1_fwd(resnetv1d_layers4_batchnorm1_fwd)
        resnetv1d_layers4_conv2_fwd = self.resnetv1d_layers4_conv2_fwd(resnetv1d_layers4_relu1_fwd)
        resnetv1d_layers4_batchnorm2_fwd = self.resnetv1d_layers4_batchnorm2_fwd(resnetv1d_layers4_conv2_fwd)
        resnetv1d_down4_pool0_fwd = self.resnetv1d_down4_pool0_fwd(resnetv1d_layers3_relu17_fwd)
        resnetv1d_down4_conv0_fwd = self.resnetv1d_down4_conv0_fwd(resnetv1d_down4_pool0_fwd)
        resnetv1d_down4_batchnorm0_fwd = self.resnetv1d_down4_batchnorm0_fwd(resnetv1d_down4_conv0_fwd)
        resnetv1d_layers4_bottleneckv1b0__plus0 = resnetv1d_layers4_batchnorm2_fwd + resnetv1d_down4_batchnorm0_fwd
        resnetv1d_layers4_relu2_fwd = self.resnetv1d_layers4_relu2_fwd(resnetv1d_layers4_bottleneckv1b0__plus0)
        resnetv1d_layers4_conv3_fwd = self.resnetv1d_layers4_conv3_fwd(resnetv1d_layers4_relu2_fwd)
        resnetv1d_layers4_batchnorm3_fwd = self.resnetv1d_layers4_batchnorm3_fwd(resnetv1d_layers4_conv3_fwd)
        resnetv1d_layers4_relu3_fwd = self.resnetv1d_layers4_relu3_fwd(resnetv1d_layers4_batchnorm3_fwd)
        resnetv1d_layers4_conv4_fwd = self.resnetv1d_layers4_conv4_fwd(resnetv1d_layers4_relu3_fwd)
        resnetv1d_layers4_batchnorm4_fwd = self.resnetv1d_layers4_batchnorm4_fwd(resnetv1d_layers4_conv4_fwd)
        resnetv1d_layers4_relu4_fwd = self.resnetv1d_layers4_relu4_fwd(resnetv1d_layers4_batchnorm4_fwd)
        resnetv1d_layers4_conv5_fwd = self.resnetv1d_layers4_conv5_fwd(resnetv1d_layers4_relu4_fwd)
        resnetv1d_layers4_batchnorm5_fwd = self.resnetv1d_layers4_batchnorm5_fwd(resnetv1d_layers4_conv5_fwd)
        resnetv1d_layers4_bottleneckv1b1__plus0 = resnetv1d_layers4_batchnorm5_fwd + resnetv1d_layers4_relu2_fwd
        resnetv1d_layers4_relu5_fwd = self.resnetv1d_layers4_relu5_fwd(resnetv1d_layers4_bottleneckv1b1__plus0)
        resnetv1d_layers4_conv6_fwd = self.resnetv1d_layers4_conv6_fwd(resnetv1d_layers4_relu5_fwd)
        resnetv1d_layers4_batchnorm6_fwd = self.resnetv1d_layers4_batchnorm6_fwd(resnetv1d_layers4_conv6_fwd)
        resnetv1d_layers4_relu6_fwd = self.resnetv1d_layers4_relu6_fwd(resnetv1d_layers4_batchnorm6_fwd)
        resnetv1d_layers4_conv7_fwd = self.resnetv1d_layers4_conv7_fwd(resnetv1d_layers4_relu6_fwd)
        resnetv1d_layers4_batchnorm7_fwd = self.resnetv1d_layers4_batchnorm7_fwd(resnetv1d_layers4_conv7_fwd)
        resnetv1d_layers4_relu7_fwd = self.resnetv1d_layers4_relu7_fwd(resnetv1d_layers4_batchnorm7_fwd)
        resnetv1d_layers4_conv8_fwd = self.resnetv1d_layers4_conv8_fwd(resnetv1d_layers4_relu7_fwd)
        resnetv1d_layers4_batchnorm8_fwd = self.resnetv1d_layers4_batchnorm8_fwd(resnetv1d_layers4_conv8_fwd)
        resnetv1d_layers4_bottleneckv1b2__plus0 = resnetv1d_layers4_batchnorm8_fwd + resnetv1d_layers4_relu5_fwd
        resnetv1d_layers4_relu8_fwd = self.resnetv1d_layers4_relu8_fwd(resnetv1d_layers4_bottleneckv1b2__plus0)
        resnetv1d_pool1_fwd = F.adaptive_avg_pool2d(resnetv1d_layers4_relu8_fwd, (1, 1))
        resnetv1d_flatten0_flatten0 = resnetv1d_pool1_fwd.view([int(resnetv1d_pool1_fwd.size(0)), -1])
        resnetv1d_dense0_fwd = self.resnetv1d_dense0_fwd(resnetv1d_flatten0_flatten0.view([int(resnetv1d_flatten0_flatten0.size(0)), -1]))
        return resnetv1d_dense0_fwd

if __name__ == '__main__':
    net = resnet50_v1d_11()
    net.load_state_dict(torch.load('resnet50_v1d_11.pt'))
    net.eval()
    print(net(torch.ones(1, 3, 224, 224)))
