import torch
import torch.nn as nn
import torch.nn.functional as F

class resnet18_v1b_89(nn.Module):
    def __init__(self):
        super(resnet18_v1b_89, self).__init__()
        self.resnetv1b_conv0_fwd = nn.Conv2d(3, 8, kernel_size=(7, 7), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(3, 3))
        self.resnetv1b_batchnorm0_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1b_relu0_fwd = nn.ReLU()
        self.resnetv1b_pool0_fwd = nn.MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), ceil_mode=False)
        self.resnetv1b_layers1_conv0_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers1_batchnorm0_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers1_relu0_fwd = nn.ReLU()
        self.resnetv1b_layers1_conv1_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers1_batchnorm1_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers1_relu1_fwd = nn.ReLU()
        self.resnetv1b_layers1_conv2_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers1_batchnorm2_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers1_relu2_fwd = nn.ReLU()
        self.resnetv1b_layers1_conv3_fwd = nn.Conv2d(8, 8, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers1_batchnorm3_fwd = nn.BatchNorm2d(8, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers1_relu3_fwd = nn.ReLU()
        self.resnetv1b_layers2_conv0_fwd = nn.Conv2d(8, 120, kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers2_batchnorm0_fwd = nn.BatchNorm2d(120, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers2_relu0_fwd = nn.ReLU()
        self.resnetv1b_layers2_conv1_fwd = nn.Conv2d(120, 56, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers2_batchnorm1_fwd = nn.BatchNorm2d(56, momentum=0.9, eps=1e-05)
        self.resnetv1b_down2_conv0_fwd = nn.Conv2d(8, 56, kernel_size=(1, 1), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1b_down2_batchnorm0_fwd = nn.BatchNorm2d(56, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers2_relu1_fwd = nn.ReLU()
        self.resnetv1b_layers2_conv2_fwd = nn.Conv2d(56, 128, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers2_batchnorm2_fwd = nn.BatchNorm2d(128, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers2_relu2_fwd = nn.ReLU()
        self.resnetv1b_layers2_conv3_fwd = nn.Conv2d(128, 56, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers2_batchnorm3_fwd = nn.BatchNorm2d(56, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers2_relu3_fwd = nn.ReLU()
        self.resnetv1b_layers3_conv0_fwd = nn.Conv2d(56, 256, kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers3_batchnorm0_fwd = nn.BatchNorm2d(256, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers3_relu0_fwd = nn.ReLU()
        self.resnetv1b_layers3_conv1_fwd = nn.Conv2d(256, 208, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers3_batchnorm1_fwd = nn.BatchNorm2d(208, momentum=0.9, eps=1e-05)
        self.resnetv1b_down3_conv0_fwd = nn.Conv2d(56, 208, kernel_size=(1, 1), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1b_down3_batchnorm0_fwd = nn.BatchNorm2d(208, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers3_relu1_fwd = nn.ReLU()
        self.resnetv1b_layers3_conv2_fwd = nn.Conv2d(208, 256, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers3_batchnorm2_fwd = nn.BatchNorm2d(256, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers3_relu2_fwd = nn.ReLU()
        self.resnetv1b_layers3_conv3_fwd = nn.Conv2d(256, 208, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers3_batchnorm3_fwd = nn.BatchNorm2d(208, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers3_relu3_fwd = nn.ReLU()
        self.resnetv1b_layers4_conv0_fwd = nn.Conv2d(208, 512, kernel_size=(3, 3), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers4_batchnorm0_fwd = nn.BatchNorm2d(512, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers4_relu0_fwd = nn.ReLU()
        self.resnetv1b_layers4_conv1_fwd = nn.Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers4_batchnorm1_fwd = nn.BatchNorm2d(512, momentum=0.9, eps=1e-05)
        self.resnetv1b_down4_conv0_fwd = nn.Conv2d(208, 512, kernel_size=(1, 1), stride=(2, 2), dilation=(1, 1), bias=False, groups=1, padding=(0, 0))
        self.resnetv1b_down4_batchnorm0_fwd = nn.BatchNorm2d(512, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers4_relu1_fwd = nn.ReLU()
        self.resnetv1b_layers4_conv2_fwd = nn.Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers4_batchnorm2_fwd = nn.BatchNorm2d(512, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers4_relu2_fwd = nn.ReLU()
        self.resnetv1b_layers4_conv3_fwd = nn.Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), dilation=(1, 1), bias=False, groups=1, padding=(1, 1))
        self.resnetv1b_layers4_batchnorm3_fwd = nn.BatchNorm2d(512, momentum=0.9, eps=1e-05)
        self.resnetv1b_layers4_relu3_fwd = nn.ReLU()
        self.resnetv1b_dense0_fwd = nn.Linear(512, 1000, bias=True)

    def forward(self, __input__0):
        resnetv1b_conv0_fwd = self.resnetv1b_conv0_fwd(__input__0)
        resnetv1b_batchnorm0_fwd = self.resnetv1b_batchnorm0_fwd(resnetv1b_conv0_fwd)
        resnetv1b_relu0_fwd = self.resnetv1b_relu0_fwd(resnetv1b_batchnorm0_fwd)
        resnetv1b_pool0_fwd = self.resnetv1b_pool0_fwd(resnetv1b_relu0_fwd)
        resnetv1b_layers1_conv0_fwd = self.resnetv1b_layers1_conv0_fwd(resnetv1b_pool0_fwd)
        resnetv1b_layers1_batchnorm0_fwd = self.resnetv1b_layers1_batchnorm0_fwd(resnetv1b_layers1_conv0_fwd)
        resnetv1b_layers1_relu0_fwd = self.resnetv1b_layers1_relu0_fwd(resnetv1b_layers1_batchnorm0_fwd)
        resnetv1b_layers1_conv1_fwd = self.resnetv1b_layers1_conv1_fwd(resnetv1b_layers1_relu0_fwd)
        resnetv1b_layers1_batchnorm1_fwd = self.resnetv1b_layers1_batchnorm1_fwd(resnetv1b_layers1_conv1_fwd)
        resnetv1b_layers1_basicblockv1b0__plus0 = resnetv1b_layers1_batchnorm1_fwd + resnetv1b_pool0_fwd
        resnetv1b_layers1_relu1_fwd = self.resnetv1b_layers1_relu1_fwd(resnetv1b_layers1_basicblockv1b0__plus0)
        resnetv1b_layers1_conv2_fwd = self.resnetv1b_layers1_conv2_fwd(resnetv1b_layers1_relu1_fwd)
        resnetv1b_layers1_batchnorm2_fwd = self.resnetv1b_layers1_batchnorm2_fwd(resnetv1b_layers1_conv2_fwd)
        resnetv1b_layers1_relu2_fwd = self.resnetv1b_layers1_relu2_fwd(resnetv1b_layers1_batchnorm2_fwd)
        resnetv1b_layers1_conv3_fwd = self.resnetv1b_layers1_conv3_fwd(resnetv1b_layers1_relu2_fwd)
        resnetv1b_layers1_batchnorm3_fwd = self.resnetv1b_layers1_batchnorm3_fwd(resnetv1b_layers1_conv3_fwd)
        resnetv1b_layers1_basicblockv1b1__plus0 = resnetv1b_layers1_batchnorm3_fwd + resnetv1b_layers1_relu1_fwd
        resnetv1b_layers1_relu3_fwd = self.resnetv1b_layers1_relu3_fwd(resnetv1b_layers1_basicblockv1b1__plus0)
        resnetv1b_layers2_conv0_fwd = self.resnetv1b_layers2_conv0_fwd(resnetv1b_layers1_relu3_fwd)
        resnetv1b_layers2_batchnorm0_fwd = self.resnetv1b_layers2_batchnorm0_fwd(resnetv1b_layers2_conv0_fwd)
        resnetv1b_layers2_relu0_fwd = self.resnetv1b_layers2_relu0_fwd(resnetv1b_layers2_batchnorm0_fwd)
        resnetv1b_layers2_conv1_fwd = self.resnetv1b_layers2_conv1_fwd(resnetv1b_layers2_relu0_fwd)
        resnetv1b_layers2_batchnorm1_fwd = self.resnetv1b_layers2_batchnorm1_fwd(resnetv1b_layers2_conv1_fwd)
        resnetv1b_down2_conv0_fwd = self.resnetv1b_down2_conv0_fwd(resnetv1b_layers1_relu3_fwd)
        resnetv1b_down2_batchnorm0_fwd = self.resnetv1b_down2_batchnorm0_fwd(resnetv1b_down2_conv0_fwd)
        resnetv1b_layers2_basicblockv1b0__plus0 = resnetv1b_layers2_batchnorm1_fwd + resnetv1b_down2_batchnorm0_fwd
        resnetv1b_layers2_relu1_fwd = self.resnetv1b_layers2_relu1_fwd(resnetv1b_layers2_basicblockv1b0__plus0)
        resnetv1b_layers2_conv2_fwd = self.resnetv1b_layers2_conv2_fwd(resnetv1b_layers2_relu1_fwd)
        resnetv1b_layers2_batchnorm2_fwd = self.resnetv1b_layers2_batchnorm2_fwd(resnetv1b_layers2_conv2_fwd)
        resnetv1b_layers2_relu2_fwd = self.resnetv1b_layers2_relu2_fwd(resnetv1b_layers2_batchnorm2_fwd)
        resnetv1b_layers2_conv3_fwd = self.resnetv1b_layers2_conv3_fwd(resnetv1b_layers2_relu2_fwd)
        resnetv1b_layers2_batchnorm3_fwd = self.resnetv1b_layers2_batchnorm3_fwd(resnetv1b_layers2_conv3_fwd)
        resnetv1b_layers2_basicblockv1b1__plus0 = resnetv1b_layers2_batchnorm3_fwd + resnetv1b_layers2_relu1_fwd
        resnetv1b_layers2_relu3_fwd = self.resnetv1b_layers2_relu3_fwd(resnetv1b_layers2_basicblockv1b1__plus0)
        resnetv1b_layers3_conv0_fwd = self.resnetv1b_layers3_conv0_fwd(resnetv1b_layers2_relu3_fwd)
        resnetv1b_layers3_batchnorm0_fwd = self.resnetv1b_layers3_batchnorm0_fwd(resnetv1b_layers3_conv0_fwd)
        resnetv1b_layers3_relu0_fwd = self.resnetv1b_layers3_relu0_fwd(resnetv1b_layers3_batchnorm0_fwd)
        resnetv1b_layers3_conv1_fwd = self.resnetv1b_layers3_conv1_fwd(resnetv1b_layers3_relu0_fwd)
        resnetv1b_layers3_batchnorm1_fwd = self.resnetv1b_layers3_batchnorm1_fwd(resnetv1b_layers3_conv1_fwd)
        resnetv1b_down3_conv0_fwd = self.resnetv1b_down3_conv0_fwd(resnetv1b_layers2_relu3_fwd)
        resnetv1b_down3_batchnorm0_fwd = self.resnetv1b_down3_batchnorm0_fwd(resnetv1b_down3_conv0_fwd)
        resnetv1b_layers3_basicblockv1b0__plus0 = resnetv1b_layers3_batchnorm1_fwd + resnetv1b_down3_batchnorm0_fwd
        resnetv1b_layers3_relu1_fwd = self.resnetv1b_layers3_relu1_fwd(resnetv1b_layers3_basicblockv1b0__plus0)
        resnetv1b_layers3_conv2_fwd = self.resnetv1b_layers3_conv2_fwd(resnetv1b_layers3_relu1_fwd)
        resnetv1b_layers3_batchnorm2_fwd = self.resnetv1b_layers3_batchnorm2_fwd(resnetv1b_layers3_conv2_fwd)
        resnetv1b_layers3_relu2_fwd = self.resnetv1b_layers3_relu2_fwd(resnetv1b_layers3_batchnorm2_fwd)
        resnetv1b_layers3_conv3_fwd = self.resnetv1b_layers3_conv3_fwd(resnetv1b_layers3_relu2_fwd)
        resnetv1b_layers3_batchnorm3_fwd = self.resnetv1b_layers3_batchnorm3_fwd(resnetv1b_layers3_conv3_fwd)
        resnetv1b_layers3_basicblockv1b1__plus0 = resnetv1b_layers3_batchnorm3_fwd + resnetv1b_layers3_relu1_fwd
        resnetv1b_layers3_relu3_fwd = self.resnetv1b_layers3_relu3_fwd(resnetv1b_layers3_basicblockv1b1__plus0)
        resnetv1b_layers4_conv0_fwd = self.resnetv1b_layers4_conv0_fwd(resnetv1b_layers3_relu3_fwd)
        resnetv1b_layers4_batchnorm0_fwd = self.resnetv1b_layers4_batchnorm0_fwd(resnetv1b_layers4_conv0_fwd)
        resnetv1b_layers4_relu0_fwd = self.resnetv1b_layers4_relu0_fwd(resnetv1b_layers4_batchnorm0_fwd)
        resnetv1b_layers4_conv1_fwd = self.resnetv1b_layers4_conv1_fwd(resnetv1b_layers4_relu0_fwd)
        resnetv1b_layers4_batchnorm1_fwd = self.resnetv1b_layers4_batchnorm1_fwd(resnetv1b_layers4_conv1_fwd)
        resnetv1b_down4_conv0_fwd = self.resnetv1b_down4_conv0_fwd(resnetv1b_layers3_relu3_fwd)
        resnetv1b_down4_batchnorm0_fwd = self.resnetv1b_down4_batchnorm0_fwd(resnetv1b_down4_conv0_fwd)
        resnetv1b_layers4_basicblockv1b0__plus0 = resnetv1b_layers4_batchnorm1_fwd + resnetv1b_down4_batchnorm0_fwd
        resnetv1b_layers4_relu1_fwd = self.resnetv1b_layers4_relu1_fwd(resnetv1b_layers4_basicblockv1b0__plus0)
        resnetv1b_layers4_conv2_fwd = self.resnetv1b_layers4_conv2_fwd(resnetv1b_layers4_relu1_fwd)
        resnetv1b_layers4_batchnorm2_fwd = self.resnetv1b_layers4_batchnorm2_fwd(resnetv1b_layers4_conv2_fwd)
        resnetv1b_layers4_relu2_fwd = self.resnetv1b_layers4_relu2_fwd(resnetv1b_layers4_batchnorm2_fwd)
        resnetv1b_layers4_conv3_fwd = self.resnetv1b_layers4_conv3_fwd(resnetv1b_layers4_relu2_fwd)
        resnetv1b_layers4_batchnorm3_fwd = self.resnetv1b_layers4_batchnorm3_fwd(resnetv1b_layers4_conv3_fwd)
        resnetv1b_layers4_basicblockv1b1__plus0 = resnetv1b_layers4_batchnorm3_fwd + resnetv1b_layers4_relu1_fwd
        resnetv1b_layers4_relu3_fwd = self.resnetv1b_layers4_relu3_fwd(resnetv1b_layers4_basicblockv1b1__plus0)
        resnetv1b_pool1_fwd = F.adaptive_avg_pool2d(resnetv1b_layers4_relu3_fwd, (1, 1))
        resnetv1b_flatten0_flatten0 = resnetv1b_pool1_fwd.view([int(resnetv1b_pool1_fwd.size(0)), -1])
        resnetv1b_dense0_fwd = self.resnetv1b_dense0_fwd(resnetv1b_flatten0_flatten0.view([int(resnetv1b_flatten0_flatten0.size(0)), -1]))
        return resnetv1b_dense0_fwd

if __name__ == '__main__':
    net = resnet18_v1b_89()
    net.load_state_dict(torch.load('resnet18_v1b_89.pt'))
    net.eval()
    print(net(torch.ones(1, 3, 224, 224)))
